routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});*/
Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware'=> 'auth'],function(){

Route::resource('/products', 'Products\ProductController');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'price', 'description', 'user_id','image'
    ];

    public function users(){
        return $this->hasmany('App\User','id', 'user_id');
    }
    public function user(){
        return $this->hasOne('App\User','id','user_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Products/ProductController.php
<?php

namespace App\Http\Controllers\Products;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\User;
use Illuminate\Support\Facades\Validator;
use Auth;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Product::with('users')->get();
        return view('product.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255', 'unique:products'],
            'description' => ['required',],
            'price' => ['required','regex:/^\d+(\.\d{1,2})?$/','between:0,99.99','max:4'],
            'file' => ['required','image','mimes:jpeg,png,jpg','max:2048'],
        ]);

        if ($request->file('file')) {
            $imagePath = $request->file('file');
            $imageName = rand(9999,999999).time().'.'.$request->file->extension();
            
            $path = $request->file->move(public_path('images'), $imageName);
            if($path){
                $createData = Product::create([
                    'name' => $request->name,
                    'price' => $request->price,
                    'description' => $request->description,
                    'image' => $imageName,
                    'user_id' => Auth::user()->id,
                ]);
                if($createData){
                    return redirect()->route('products.index')->with('success', 'Product Added Successfully.');
                }
                    return redirect()->route('products.create')->with('error', 'Product Not Added.');
            }
            return redirect()->route('products.create')->with('error', 'Product Not Added.');
        }
        return redirect()->route('products.create')->with('error', 'Product Not Added.');;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $id = decrypt($id);
        $data = Product::where('id',$id)->with('user')->first();
        return view('product.view',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $id = decrypt($id);
        $data = Product::where('id',$id)->with('user')->first();

        if($data->user_id !== (int)Auth::user()->id){
            return redirect()->route('products.index')->with('error','You have not permission to edit this product');
        }
        return view('product.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'description' => ['required'],
            'price' => ['required','regex:/^\d+(\.\d{1,2})?$/'],
        ]);
        $id = decrypt($id);
        $update = Product::find($id)->update([
            'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
        ]);
        if($update){
            return redirect()->route('products.index')->with('success', 'Product Updated Successfully.');
        }
            return redirect()->route('products.create')->with('error', 'Product Not Added.');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $id = decrypt($id);
        $data = Product::where('id',$id)->with('user')->first();

        if($data->user_id !== (int)Auth::user()->id){
            return redirect()->route('products.index')->with('error','You have not permission to delete this product');
        }
        $data = Product::find($id)->delete();
        if($data){
            return redirect()->route('products.index')->with('success','Product deleted successfully.');
        }
        return redirect()->route('products.index')->with('error','Product not found.');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/custom.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('products.index') }}">{{ __('Products') }}</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                @if (\Session::has('error'))
                    <p class="alert alert-danger">
                        {!! \Session::get('error') !!}
                    </p>
                @endif
                <div class="card-header">{{ __('Add Products') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}"  autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}"  autocomplete="price">

                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="file" class="col-md-4 col-form-label text-md-right">{{ __('Image') }}</label>

                            <div class="col-md-6">
                                <input id="file" type="file" class="form-control @error('file') is-invalid @enderror" name="file" value="{{ old('file') }}"  autocomplete="file" autofocus>

                                @error('file')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" autocomplete="description">{{ old('description') }}</textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Add') }}
                                </button>
                                <a href="{{ route('products.index') }}" class="btn btn-primary">
                                    {{ __('Clear') }}
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                @if (\Session::has('error'))
                    <p class="alert alert-danger">
                        {!! \Session::get('error') !!}
                    </p>
                @endif
                <div class="card-header">{{ __('View Products Details') }}
                    <a href="{{ route('products.index') }}" class="btn btn-success btn-sm float-right">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('products.update',['product' => encrypt($data->id)]) }}">
                        @method('PUT')
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" readonly="" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $data->name }}"  autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ $data->price }}"  autocomplete="price">

                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" autocomplete="description">{{ $data->description }}</textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="createdBy" class="col-md-4 col-form-label text-md-right">{{ __('Created By') }}</label>

                            <div class="col-md-6">
                                <input readonly="" id="createdBy" class="form-control @error('createdBy') is-invalid @enderror" name="createdBy" autocomplete="createdBy" value = "{{ $data->users ? $data->users[0]->name : '' }}" >

                                @error('createdBy')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                                <a href="{{ route('products.index') }}" class="btn btn-danger">
                                    {{ __('Clear') }}
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
            	@if (\Session::has('success'))
				    <div class="alert alert-success">
				        <ul>
				            <li>{!! \Session::get('success') !!}</li>
				        </ul>
				    </div>
				@endif
				@if (\Session::has('error'))
				    <div class="alert alert-danger">
				        <ul>
				            <li>{!! \Session::get('error') !!}</li>
				        </ul>
				    </div>
				@endif
            	<div class="card-header">
            		{{ __('Products List') }}
            		<a href="{{ route('products.create') }}" class="btn btn-success float-right">{{ __('Add Product') }}</a>
            	</div>
            	<div class="card-body">
            		<main>
					    <div class="container-fluid bg-trasparent my-4 p-3" style="position: relative;">
					        <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
					        	@forelse($data as $productKey => $productValue)
						            <div class="col">
						                <div class="card h-100 shadow-sm"> <img src="{{ asset('/images') }}/{{ $productValue->image }}" class="card-img-top" alt="...">
						                    <div class="card-body">
						                        <div class="clearfix mb-3"> 
						                        	<span class="float-start badge rounded-pill bg-primary">{{ $productValue->name }}</span> 
						                        	<span class="float-end price-hp">$ {{ $productValue->price }}</span> 
						                        </div>
						                        <h5 class="card-title text-justify">{{ $productValue->description }}</h5>
						                        <div class="text-center my-4">
						                        	<span>Created by :- </span> 
						                        	<a href="#" class="btn btn-warning btn-sm">{{ $productValue->users ? $productValue->users[0]->name : '' }} {{ date('d-m-Y', strtotime($productValue->created_at)) }} </a> </div>
						                        <a href="{{ route('products.show',['product' => encrypt($productValue->id) ]) }}" class="btn btn-secondary btn-sm">{{ __('View') }}</a>
									        	<a href="{{ route('products.edit', ['product' => encrypt($productValue->id) ]) }}" class="btn btn-success btn-sm">{{ __('Edit') }}</a>
									        	<a href="{{ route('products.destroy', ['product' => encrypt($productValue->id) ]) }}" class="btn btn-danger btn-sm deleteProduct" data-id="{{ encrypt($productValue->id) }}">{{ __('Delete') }}</a>
						                    </div>
						                </div>
						            </div>
						        @empty
						        	<p class="text-danger text-center">Data not found</p>
						        @endforelse
					        </div>
					    </div>
					</main>
            		<!-- <div class="table-responsive">
					  <table class="table">
					    <thead>
					      <tr>
					        <th scope="col">#</th>
					        <th scope="col">{{ __('Name') }}</th>
					        <th scope="col">{{ __('Price') }}</th>
					        <th scope="col">{{ __('Description') }}</th>
					        <th scope="col">{{ __('Created by') }}</th>
					        <th scope="col">{{ __('Actions') }}</th>
					      </tr>
					    </thead>
					    <tbody>
					    	@forelse($data as $productKey => $productValue)
						      <tr>
						        <th scope="row">{{$productKey+1}}</th>
						        <td>{{ $productValue->name }}</td>
						        <td>{{ $productValue->price }}</td>
						        <td>{{ $productValue->description }}</td>
						        <td>{{ $productValue->users ? $productValue->users[0]->name : '' }}</td>
						        <td>
						        	<a href="{{ route('products.show',['product' => encrypt($productValue->id) ]) }}" class="btn btn-secondary btn-sm">{{ __('View') }}</a>
						        	<a href="{{ route('products.edit', ['product' => encrypt($productValue->id) ]) }}" class="btn btn-success btn-sm">{{ __('Edit') }}</a>
						        	<a href="{{ route('products.destroy', ['product' => encrypt($productValue->id) ]) }}" id="{{encrypt($productValue->id)}}" class="btn btn-danger btn-sm deleteProduct">{{ __('Delete') }}</a>
						        {{ __('') }}</td>
						      </tr>
						     @empty
						     	<td colspan="6" class="text-danger text-center">Data not found</td>
						    @endforelse
					    </tbody>
					  </table>
					</div> -->
            	</div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                @if (\Session::has('error'))
                    <p class="alert alert-danger">
                        {!! \Session::get('error') !!}
                    </p>
                @endif
                <div class="card-header">{{ __('View Products Details') }}
                    <a href="{{ route('products.index') }}" class="btn btn-success btn-sm float-right">{{ __('Back') }}</a>
                </div>

                <div class="card-body">
                    <!--Section: Block Content-->
                    <div class="col-md-12">
                        <div class="col">
                            <div class="card col-md- 6shadow-sm"> 
                                <img src="{{ asset('images')}}/{{ $data->image }}" class="img-fluid mx-auto my-auto card-img-top" alt="...">
                                <div class="card-body text-center">
                                    <div class="clearfix mb-3"> 
                                        <span class="float-start badge rounded-pill bg-primary">{{ $data->name }}</span> 
                                        <span class="float-end price-hp">$ {{ $data->price }}</span> 
                                    </div>
                                    <h5 class="card-title border border-1 text-justify">{{ $data->description }}</h5>
                                    <div class="text-center my-4">
                                        <span>Created by : </span>
                                        <a href="#" class="btn btn-warning">{{ $data->users ? $data->users[0]->name : '' }}</a> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection